[company]
logo_path = "logo.png"
name = "Company name"
person_name = "Jean Dagedru"
address = "1 rue des Champs Elysées, 75000 Paris"
email = "someaddress@gmail.com"
legal_status = "SARL"
siret_number = "010203040506070809"

[bank]
name = "Bank name"
iban = "IBAN"
bic = "BIC"

[invoice]
add_iban = true
footer = ""
tax_applicable = false
tax_rate = 0.2
