months = [
  "Janvier",
  "Février",
  "Mars",
  "Avril",
  "Mai",
  "Juin",
  "Juillet",
  "Août",
  "Septembre",
  "Octobre",
  "Novembre",
  "Décembre"
]

[general]
currency_symbol = "€"

tax_name = "TVA"
tax_not_applicable = "Tax non applicable"

total_price_no_tax = "Total HT"
total_price_with_tax = "Total TTC"

creation_date = "Créée le"
sell_date = "Vente réalisée le"

tx_item_description = "Description"
tx_units = "Unités"
tx_price_per_unit = "Prix unitaire"

iban_bank = "Nom"
iban_title = "Coordonnées bancaires"

[invoice]
recipient_intro = "Facturé à"
invoice_nb = "Facture numéro"

[quotation]
recipient_intro = "Devis addressé à"
quotation_nb = "Devis numéro"
payment_conditions = "Conditions de paiement"
